# Stage 1: Build the React app
FROM node:17-alpine AS build

# Install build dependencies (including Python3 for node-gyp issues)
RUN apk add --no-cache python3 make g++

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the necessary dependencies
RUN npm install

# Copy the rest of the application’s source code to the working directory
COPY . .

# Build the application
RUN npm run build

# Build the application with prod flag

RUN npm run build --prod

# Stage 2: Serve the React app using NGINX
FROM nginx:alpine

# Copy the build output to NGINX's html directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose the default NGINX port
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]